version: "2"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=mydb

  backup:
    build: .
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=mydb
      - POSTGRES_HOST=db
      - DROPBOX_ACCESS_TOKEN=XJSmdEHZdVUAAAAAAAALck58f3FbTv3dl2nS61VnL0VGRJCPA24IPTLCfAevZs2H 
